server:
#  servlet:
#    context-path: /inventory-system
  port: 8080

spring:
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123
    druid:
      filters: stat,wall
      max-active: 20
      initial-size: 5
      max-wait: 60000
      min-idle: 5
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      remove-abandoned-timeout: 1800
  data:
    # 引入es
    elasticsearch:
    # elasticsearch集群名称，默认的是elasticsearch
      cluster-name: elasticsearch
      #节点的地址 注意api模式下端口号是9300，千万不要写成9200
      cluster-nodes: localhost:9300
      #是否开启本地存储
      repositories:
        enabled: true

# 配置slq打印日志
mybatis-plus:
  #xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）com/cdc/inventorysystem/mapper/
  # 如果是放在src/main/java目录下 classpath:/com/*/*/mapper/*Mapper.xml 
#   如果是放在resource目录 classpath:/mapper/**.xml
  mapper-locations: classpath:/mapper/**.xml
  #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.cdc.inventorysystem.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl